accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView

from accountapp.views import AccountCreateView, AccountUpdateView, AccountDeleteView, \
    AccountDetailView, AccountModelViewSet
from django.urls import path
from django.urls.conf import include

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='accountapp/logout.html'), name='logout'),

    path('signup/', AccountCreateView.as_view(), name='signup'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

    path('accounts', AccountModelViewSet.as_view({"get": "list", "post": "create"})),
    path('accounts/<int:pk>', AccountModelViewSet.as_view({"get": "retrieve", "delete": "destroy", "put": "update"})),
]

chatapp/urls.py
# chatapp/urls.py
from django.urls import path, re_path

from .views import main, enter_room

app_name = "chatapp"

urlpatterns = [
    path('', enter_room, name='enter_room'),
    re_path('(?P<room_name>.*)$', main, name='main')
]

nerdneck/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include

import measurementapp.views
from accountapp.views import homeView
from nerdneck import settings

urlpatterns = [
    path('', homeView, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('chat/', include('chatapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin, ListView
from rest_framework import serializers, generics, viewsets
from rest_framework.response import Response

from accountapp.decorator import account_ownership_required
from accountapp.forms import AccountUpdateForm
from django.urls import reverse, reverse_lazy
from django.http.response import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

has_ownership = [account_ownership_required, login_required]


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('home')
    template_name = 'accountapp/signup.html'


class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

    paginate_by = 25

    def get_context_data(self, **kwargs):
        object_list = ['test1', 'test2', 'test3']
        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/update.html'

    # def get(self, *args, **kwargs):
    #     if self.request.user.is_authenticated and self.get_object() == self.request.user:
    #         return super().post(*args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()
    #
    # def post(self, *args, **kwargs):
    #     if self.request.user.is_authenticated and self.get_object() == self.request.user:
    #         return super().post(*args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

    # def get(self, *args, **kwargs):
    #     if self.request.user.is_authenticated and self.get_object() == self.request.user:
    #         return super().post(*args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()
    #
    # def post(self, *args, **kwargs):
    #     if self.request.user.is_authenticated and self.get_object() == self.request.user:
    #         return super().post(*args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()


class AccountSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ('username', 'date_joined', 'is_staff')

class AccountModelViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = AccountSerializer

def homeView(request):
    return render(request, 'accountapp/home.html')


accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}
    <div style="text-align: center; max-width:500px; margin:4rem auto">
        <div class="mb-4">
            <h4>Quit</h4>
        </div>

        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-4">
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <div style="text-align: center; max-width: 500px; margin:4rem auto">
      <h4>Detail</h4>
      {% if target_user.profile %}
            <img src="{{ target_user.profile.image.url }}" alt=""
           style="height:12rem; width:12rem; border-radius: 10rem; margin-bottom: 2rem; object-fit:cover;" >
      <h2>
        {{ target_user.profile.nickname }}
          {% if target_user == user %}
          <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
            edit
          </a>
          {% endif %}
      </h2>
      <h5 style="margin-bottom:3rem"> {{ target_user.profile.message }} </h5>

      {% else %}
        {% if target_user == user %}
        <a href="{% url 'profileapp:create' %}">
          <h2>
            Create Profile
          </h2>
        </a>
        {% else %}
        <h2>
          표시할 정보가 없습니다.
        </h2>
        {% endif %}
      {% endif %}


      {% if target_user == user %}
      <a href="{% url 'accountapp:update' pk=user.pk %}">
        <p>
          Change Info
        </p>
      </a>
      <a href="{% url 'accountapp:delete' pk=user.pk %}">
        <p>
          Quit
        </p>
      </a>
      {% endif %}
      </div>
      <hr>

  </div>
{% endblock %}

accountapp/templates/accountapp/home.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width:500px; margin:4rem auto">
        <img src="media/turtle/turtle.jpg" alt=""
           style="height:12rem; width:12rem; border-radius: 3rem; margin-bottom: 2rem; object-fit:cover;" >
        <div>
            <span style="color:red; font-size:2.0rem; font-family: 'Raleway', sans-serif; margin-bottom: 1.2rem; margin-right: 0rem">N</span><span style = "font-size: 2.0rem; font-family: 'Raleway', sans-serif; margin-bottom: 1.8rem;">erdNeck</span>
            <br>
            <span style = "font-size: 1.3rem; font-family: 'Raleway', sans-serif; margin-bottom: 1.8rem;">Video Chat</span>
            <br>
            <h6 style="margin-top: 1.2rem">Ready To Check NerdNeck?</h6>
        </div>
        <div>
            <a href="{% url 'chatapp:enter_room' %}" class="btn btn-dark rounded-pill col-5 mt-4">
                Let's Goo!
            </a>
        </div>
    </div>
    {% if not user.is_authenticated %}
    <div style="text-align: center;">

    </div>
    {% endif %}
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}

{% block content %}
    <div style="text-align: center; max-width:500px; margin:4rem auto">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">

                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-4">
            </form>
            <a href="{% url 'accountapp:signup' %}" class="btn btn-dark rounded-pill col-6 mt-4">
                회원가입
            </a>
        </div>
    </div>
    {% if not user.is_authenticated %}
    <div style="text-align: center;">

    </div>
    {% endif %}
{% endblock %}

accountapp/templates/accountapp/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width:500px; margin:4rem auto">
        <div class="mb-4">
            <h4>SignUp</h4>
        </div>

        <form action="{% url 'accountapp:signup' %}" method="POST">
            {% csrf_token %}
<!--            {{ form }}-->
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-4">
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width:500px; margin:4rem auto">
        <div class="mb-4">
            <h4>Update</h4>
        </div>

        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-4">
        </form>
    </div>
{% endblock %}