accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView

from accountapp.views import AccountCreateView, AccountUpdateView, AccountDeleteView, \
    AccountDetailView, AccountModelViewSet
from django.urls import path
from django.urls.conf import include

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='accountapp/logout.html'), name='logout'),

    path('signup/', AccountCreateView.as_view(), name='signup'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

    path('accounts', AccountModelViewSet.as_view({"get": "list", "post": "create"})),
    path('accounts/<int:pk>', AccountModelViewSet.as_view({"get": "retrieve", "delete": "destroy", "put": "update"})),
]

chatapp/urls.py
# chatapp/urls.py
from django.urls import path, re_path

from .views import main, enter_room

app_name = "chatapp"

urlpatterns = [
    path('', enter_room, name='enter_room'),
    re_path('(?P<room_name>.*)$', main, name='main')
]

nerdneck/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include

import measurementapp.views
from accountapp.views import homeView
from nerdneck import settings

urlpatterns = [
    path('', homeView, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('chat/', include('chatapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang = "ko">

{% include 'head.html' %}

<body style="height: 100vh;">
    {% include 'header.html' %}
    <hr>

    {% block content %}


    {% endblock %}

    <hr>
    {% include 'footer.html' %}
           
</body>
</html>

templates/footer.html
<div style="text-align: center; margin-top: 2rem;">
    <div style="font-size: .6rem;">
        <a href="https://github.com/Nerd-Neck-GIST/Nerd-Neck-Server">Docs</a> |
        <a href="https://www.notion.so/Juchan-Lee-1d7510dfdc894025ab1b98a709f00a80">Team</a> |
        <a href="https://drive.google.com/drive/folders/1y0CoXwX-xebq3dtqbLJWLHJBOv6ogtPc?usp=share_link">Service</a>
    </div>
    <div style="margin-top: 1rem; height:100px;">
        <span style="color:red; font-size:1.2rem; font-family: 'Raleway', sans-serif; margin-bottom: 1.2rem; margin-right: 0rem">N</span><span style = "font-size: 1.0rem; font-family: 'Raleway', sans-serif; margin-bottom: 1.8rem;">erdNeck</span>
    </div>
</div>
     

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Django Channels webrtc</title>
    <!-- BOOTSTRAP LINK -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <!-- GOOGLE FONTS LINK -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@600&display=swap" rel="stylesheet">

    <!-- DEFAULT CSS LINK -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <meta name ="google-signin-client_id" content="1013766092116-92dh6nq19v0c30ganfdflm3edq5fco6l.apps.googleusercontent.com">

	<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.11.0/dist/tf.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/posenet@2.2.2/dist/posenet.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core@3.11.0/dist/tf-core.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-converter@3.11.0/dist/tf-converter.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgl@3.11.0/dist/tf-backend-webgl.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/pose-detection@0.0.6/dist/pose-detection.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<style>
		#modal.modal-overlay {
		  width: 100%;
		  height: 100%;
		  position: absolute;
		  left: 0;
		  top: 0;
		  display: flex;
		  flex-direction: column;
		  align-items: center;
		  justify-content: center;
		  background: rgba(255, 255, 255, 0.25);
		  box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
		  backdrop-filter: blur(1.5px);
		  -webkit-backdrop-filter: blur(1.5px);
		  border-radius: 10px;
		  border: 1px solid rgba(255, 255, 255, 0.18);
		}
		#modal .modal-window {
			background: rgba( 69, 139, 197, 0.70 );
			box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );
			backdrop-filter: blur( 13.5px );
			-webkit-backdrop-filter: blur( 13.5px );
			border-radius: 10px;
			border: 1px solid rgba( 255, 255, 255, 0.18 );
			width: 400px;
			height: 200px;
			position: relative;
			top: -100px;
			padding: 10px;
			text-align: center;
			line-height: 100px;
		}
		#modal .title {
	
			display: inline;
			text-shadow: 1px 1px 2px gray;
			color: white;
			
		}
		#modal .title h2 {
			display: inline;
		}
		#modal .close-area {
			display: inline;
			float: right;
			padding-right: 10px;
			cursor: pointer;
			text-shadow: 1px 1px 2px gray;
			color: white;
		}
	
		#modal .content {
			margin-top: 10px;
			padding: 0px 10px;
			text-shadow: 1px 1px 2px gray;
			color: white;
		}
	  </style>
</head>

templates/header.html
<div style="text-align: center; margin:2rem 0;">
    <div style="margin-bottom: 1.2rem;">
        <span style="color:red; font-size:1.8rem; font-family: 'Raleway', sans-serif; margin-bottom: 1.8rem; margin-right: 0rem">N</span><span style = "font-size: 1.5rem; font-family: 'Raleway', sans-serif; margin-bottom: 1.8rem;">erdNeck</span>
        <br>
        <span style = "color:black; font-size:1.0rem; font-family: 'Raleway', sans-serif; margin-bottom: 1.8rem;">- </span><span style="color:red; font-size:1.0rem; font-family: 'Raleway', sans-serif; margin-bottom: 1.8rem; margin-right: 0rem">G</span><span style = "color:#656565; font-size:1.0rem; font-family: 'Raleway', sans-serif; margin-bottom: 1.8rem;">IST</span><span style = "color:black; font-size:1.0rem; font-family: 'Raleway', sans-serif; margin-bottom: 1.8rem;">Computer Networking</span><span style = "color:black; font-size:1.0rem; font-family: 'Raleway', sans-serif; margin-bottom: 1.8rem;"> -</span>
    </div>
    <div>
        {% if not user.is_authenticated %}
        <a href="{% url 'home' %}?next={{ request.path }}" style="color:black; text-decoration-line: none; font-family: 'Raleway', sans-serif; padding: 1rem">
            <span>Home</span>
        </a>
        <a href="{% url 'accountapp:login' %}" style="color:black; text-decoration-line: none; font-family: 'Raleway', sans-serif; padding: 1rem">
<!--            ?next={{ request.path }}-->
            <span>Login</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}" style="color:black; text-decoration-line: none; font-family: 'Raleway', sans-serif; padding: 1rem">
            <span>MyPage</span>
        </a>
        <a href="{% url 'home' %}?next={{ request.path }}" style="color:black; text-decoration-line: none; font-family: 'Raleway', sans-serif; padding: 1rem">
            <span>Home</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" style="color:black; text-decoration-line: none; font-family: 'Raleway', sans-serif; padding: 1rem">
            <span>Logout</span>
        </a>
        <div style="margin-top: 1rem; font-family: 'Raleway', sans-serif;">
            <h6>Hello <a href="{% url 'accountapp:detail' pk=user.pk %}" style="color:gray; text-decoration-line: none; font-family: 'Raleway', sans-serif;">{{ user.username }}</a>!</h6>
        </div>
        {% endif %}
    </div>

</div>